FROM python:3.11-alpine

ARG RED_VERSION

ENV PYTHONUNBUFFERED=1

LABEL org.opencontainers.image.authors="tigattack"
LABEL org.opencontainers.image.title="Red Discord Bot"
LABEL org.opencontainers.image.description="Alpine-based Red Discord Bot container image."
LABEL org.opencontainers.image.version="${RED_VERSION}"
LABEL org.opencontainers.image.url="https://github.com/rHomelab/Red-DiscordBot-Docker"
LABEL org.opencontainers.image.documentation="https://github.com/rHomelab/Red-DiscordBot-Docker/blob/main/README.md"
LABEL org.opencontainers.image.source="https://github.com/rHomelab/Red-DiscordBot-Docker"

ENV PATH="/home/redbot/.local:/home/redbot/.local/bin:${PATH}"

RUN apk add --no-cache build-base git openjdk11-jre-headless libffi-dev units

RUN addgroup -g 1024 -S redbot && \
   adduser -SG redbot redbot

COPY requirements.txt redbot.sh /redbot/

RUN mkdir -pv /redbot/data /home/redbot/.local/share/ && \
   ln -sv /redbot/data /usr/local/share/Red-DiscordBot && \
   ln -sv /redbot/data /home/redbot/.local/share/Red-DiscordBot && \
   chown -Rv redbot:redbot /redbot /home/redbot && \
   chmod -v +x /redbot/redbot.sh

USER redbot

RUN python -m pip install --no-cache-dir --upgrade --user -r /redbot/requirements.txt

VOLUME ["/redbot/data"]

ENTRYPOINT ["/redbot/redbot.sh"]
