FROM python:3.11-slim-bullseye

ARG RED_VERSION

ENV PYTHONUNBUFFERED=1

LABEL org.opencontainers.image.authors="tigattack, dantho281"
LABEL org.opencontainers.image.title="Red Discord Bot"
LABEL org.opencontainers.image.description="Debian-based Red Discord Bot container image."
LABEL org.opencontainers.image.version="${RED_VERSION}"
LABEL org.opencontainers.image.url="https://github.com/rHomelab/Red-DiscordBot-Docker"
LABEL org.opencontainers.image.documentation="https://github.com/rHomelab/Red-DiscordBot-Docker/blob/main/README.md"
LABEL org.opencontainers.image.source="https://github.com/rHomelab/Red-DiscordBot-Docker"

ENV PATH="/home/redbot/.local:/home/redbot/.local/bin:${PATH}"

ARG DEBIAN_FRONTEND=noninteractive

COPY requirements.txt redbot.sh /redbot/

RUN apt-get update && \
   apt-get --no-install-recommends -y install build-essential git openjdk-11-jre-headless units && \
   rm -rf /var/lib/apt/lists/* && \
   groupadd -r redbot -g 1024 && \
   useradd  -r -m -g redbot redbot && \
   mkdir -pv /redbot/data /home/redbot/.local/share/ && \
   ln -sv /redbot/data /usr/local/share/Red-DiscordBot && \
   ln -sv /redbot/data /home/redbot/.local/share/Red-DiscordBot && \
   chown -Rv redbot:redbot /redbot /home/redbot && \
   chmod -v +x /redbot/redbot.sh && \
   su - redbot -c "python -m pip install --no-cache-dir --upgrade --user -r /redbot/requirements.txt" && \
   apt-get remove -y build-essential && \
   apt-get autoremove -y

USER redbot

VOLUME ["/redbot/data"]

ENTRYPOINT ["/redbot/redbot.sh"]
